# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FizzBuzz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FizzBuzz
  pod 'SAConfettiView', :git => 'https://github.com/gokhanakkurt/SAConfettiView.git', :branch => 'swift3'

end
